-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE staging."softcartDimDate"
(
    dateid integer NOT NULL,
    day date NOT NULL,
    weekday integer NOT NULL,
    weekdayname character varying(20) NOT NULL,
    year integer NOT NULL,
    month integer NOT NULL,
    monthname character varying(20) NOT NULL,
    quarter integer NOT NULL,
    quartername character varying(20) NOT NULL,
    PRIMARY KEY (dateid)
);

CREATE TABLE staging."softcartDimCategory"
(
    categoryid integer NOT NULL,
    categoryname character varying(20) NOT NULL
);

CREATE TABLE staging."softcartDimItem"
(
    itemid integer NOT NULL,
    itemname character varying(200) NOT NULL,
    categoryid integer NOT NULL,
    price numeric(9, 3) NOT NULL,
    PRIMARY KEY (itemid)
);

CREATE TABLE staging."softcartDimCountry"
(
    countryid integer NOT NULL,
    countryname character varying(20) NOT NULL,
    PRIMARY KEY (countryid)
);

CREATE TABLE staging."softcartFactSales"
(
    orderid integer NOT NULL,
    itemid integer NOT NULL,
    countryid integer NOT NULL,
    dateid integer NOT NULL,
    PRIMARY KEY (orderid)
);
END;
